#include "global_data.h"

volatile uint32_t g_positionControllerX;
volatile uint32_t g_positionControllerXMaxValue;
volatile uint32_t g_positionControllerXDesiredValue;
volatile positionControllerStatus_t g_positionControllerXStatus;
volatile positionControllerDirection_t g_positionControllerXDirection;

volatile clientUartRequest_t g_clientUartRxBuffer;
volatile clientUartResponse_t g_clientUartTxBuffer;
