#pragma once

#define IRQ_PRIORITY_EMERGENCY_BUTTON             1
#define IRQ_PRIORITY_MOTOR_PWM_STOP               2
#define IRQ_PRIORITY_CLIENT_DMA2_CHANNEL7_RX      3
#define IRQ_PRIORITY_CLIENT_DMA2_CHANNEL6_TX      4
