#pragma once

#define IRQ_PRIORITY_EMERGENCY_BUTTON             1
#define IRQ_PRIORITY_MOTOR_PWM_STOP               2
#define IRQ_PRIORITY_LINE_SENSOR_SPI              3
#define IRQ_PRIORITY_LINE_SENSOR_DMI2_CHANNEL1_RX 4
#define IRQ_PRIORITY_LINE_SENSOR_DMI2_CHANNEL2_TX 4
