#pragma once

#define IRQ_PRIORITY_EMERGENCY_BUTTON             1
#define IRQ_PRIORITY_MOTOR_PWM_STOP               2
#define IRQ_PRIORITY_CLIENT_DMA2_CHANNEL7_RX      3
#define IRQ_PRIORITY_CLIENT_DMA2_CHANNEL6_TX      4
#define IRQ_PRIORITY_LINE_SENSOR_SPI              5
#define IRQ_PRIORITY_LINE_SENSOR_DMA2_CHANNEL1_RX 6
#define IRQ_PRIORITY_LINE_SENSOR_DMA2_CHANNEL2_TX 6
