#pragma once

#define IRQ_PRIORITY_EMERGENCY_BUTTON 1
#define IRQ_PRIORITY_LIMIT_SWITCH     2
#define IRQ_PRIORITY_MOTOR_PWM_DMA    3
#define IRQ_PRIORITY_MOTOR_PWM_STOP   3
#define IRQ_PRIORITY_CLIENT_RX        4
#define IRQ_PRIORITY_CLIENT_TX        5
